FROM node:lts AS development
WORKDIR /frontend
COPY package.json /frontend/package.json
COPY package-lock.json /frontend/package-lock.json
RUN npm install
COPY . /frontend

ENV PORT=3000

CMD ["npm", "start"]

FROM development AS build
RUN npm run build

FROM development AS dev-envs
RUN <<EOF
apt-get update
apt-get install -y --no-install-recommends git
EOF

RUN <<EOF
useradd -s /bin/bash -m dockroot
groupadd docker
usermod -aG dockroot vscode
EOF

COPY --from=gloursdocker/docker / /
CMD ["npm", "start"]

FROM nginx:alpine

COPY --from=build /frontend/nginx/nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /usr/share/nginx/html

RUN rm -rf ./*

COPY --from=build /frontend/build .

ENTRYPOINT ["nginx", "-g", "daemon off;"]