version: '3.8'
services:  
  postgres_db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-carthread}
      - POSTGRES_USER=${POSTGRES_USER:-postgresadmin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-Ez3b&N7_ecdjIU$2513?5fOf@43V}
    volumes:
      - pgdata1:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d carthreadsdata"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: backend
    ports:
      - '8080:80'
    volumes:
      - ./backend:/index
    stdin_open: true
    tty: true
  client:
    build: ./frontend
    container_name: frontend
    ports:
      - '80:80'
    volumes:
      - ./frontend:/index
volumes:
  pgdbdata: {}