version: "3.9"

services:
  db:
    container_name: db
    image: postgres:12
    environment:
      - POSTGRES_DB=djdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=nddr6444
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data:rw

  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - PG_USER=root
      - PG_PASSWORD=nddr6444
      - PG_DB=djdb
      - PG_PORT=5432
      - PG_HOST=db
    depends_on:
      - db

volumes:
  pgdata: {}
